<a href="https://colab.research.google.com/github/AnushaSanoop/Data-Science/blob/master/co1_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr=np.array([5,1,2])
print("Array type of ",arr," = ",type(arr))
print("Shape of ",arr," = ",arr.shape)
a1=np.array([1])
print(a1)
arr.ndim


Array type of  [5 1 2]  =  <class 'numpy.ndarray'>
Shape of  [5 1 2]  =  (3,)
[1]


1

In [ ]:
a2=np.array([[2,1,3,4],[8,9,6,7]])
print("Array type of ",a2," = ",type(a2))
print("Shape of ",a2," = ",a2.shape)
print("Dimnsion of ",a2," = ",a2.ndim)
a2.shape=4,2
print("Shape of ",a2," = ",a2.shape)

Array type of  [[2 1 3 4]
 [8 9 6 7]]  =  <class 'numpy.ndarray'>
Shape of  [[2 1 3 4]
 [8 9 6 7]]  =  (2, 4)
Dimnsion of  [[2 1 3 4]
 [8 9 6 7]]  =  2
[[2 1 3 4]
 [8 9 6 7]]
[[2 1]
 [3 4]
 [8 9]
 [6 7]]
Shape of  [[2 1]
 [3 4]
 [8 9]
 [6 7]]  =  (4, 2)


In [ ]:
#reshape

a=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print(a)
print(a.reshape(3,5))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [ ]:
#resize

a=np.array([1,2,3,4])
print("Original",a)
a.resize(2,4)
print(a)


Original [1 2 3 4]
[[1 2 3 4]
 [0 0 0 0]]


In [ ]:
a = np.array([[1,2], [3,4]])
np.resize(a, (2,3))

array([[1, 2, 3],
       [4, 1, 2]])

In [ ]:
l=[1,2,3,4,5]
l_arr=np.array(l)
print("List ",l," into an array= ",l_arr)
t=(4,5,6)
t_arr=np.array(t)
print("Tuple ",t," into an array= ",t_arr)

List  [1, 2, 3, 4, 5]  into an array=  [1 2 3 4 5]
Tuple  (4, 5, 6)  into an array=  [4 5 6]


In [ ]:
ze=np.zeros((3,2),dtype=int)
print(ze)
on=np.ones((2,4),dtype=int)
print(on)

[[0 0]
 [0 0]
 [0 0]]
[[1 1 1 1]
 [1 1 1 1]]


In [ ]:
identityMatrix=np.eye(3,dtype=int)
print(identityMatrix)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
#arange function

n=np.arange(10,20)
print(n)
n1=np.arange(1,20,2)
print(n1)
n1=np.arange(1,20,3)
print(n1)

[10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]
[ 1  4  7 10 13 16 19]


In [ ]:
#Operations

a=np.array([1,4,12,8])
b=np.array([6,8,12,76])
print(a,"+",b,"=",np.add(a,b))
print(np.sum([a]))
print(np.sum([b]))
print(np.sum([a,b]))


print(b,"-",a,"=",np.subtract(b,a))
print(b,"/",a,"=",np.divide(b,a))
print(b,"/",a,"=",np.divmod(b,a))
print(a,"**2","=",np.power(a,2))

[ 1  4 12  8] + [ 6  8 12 76] = [ 7 12 24 84]
25
102
127
[ 6  8 12 76] - [ 1  4 12  8] = [ 5  4  0 68]
[ 6  8 12 76] / [ 1  4 12  8] = [6.  2.  1.  9.5]
[ 6  8 12 76] / [ 1  4 12  8] = (array([6, 2, 1, 9]), array([0, 0, 0, 4]))
[ 1  4 12  8] **2 = [  1  16 144  64]
