<a href="https://colab.research.google.com/github/AnushaSanoop/Data-Science/blob/master/Matrix%20operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Python code to demonstrate matrix operations
# multiply() and dot()
  
# importing numpy for matrix operations
import numpy
  
# initializing matrices
x = numpy.array([[1, 2], [4, 5]])
y = numpy.array([[7, 8], [9, 10]])
  
# using multiply() to multiply matrices element wise
print ("The element wise multiplication of matrix is : ")
print (numpy.multiply(x,y))
  
# using dot() to multiply matrices
print ("The product of matrices is : ")
print (numpy.dot(x,y))

The element wise multiplication of matrix is : 
[[ 7 16]
 [36 50]]
The product of matrices is : 
[[25 28]
 [73 82]]


In [3]:
# using "T" to transpose the matrix
print("Given matrix:")
print(x)
print ("The transpose of given matrix is : ")
print (x.T)

Given matrix:
[[1 2]
 [4 5]]
The transpose of given matrix is : 
[[1 4]
 [2 5]]


In [5]:
# using "trace" to find trace of the matrix
print ("The trace of given matrix is : ")
print (x.trace())

The trace of given matrix is : 
6


In [6]:
#Rank of matrix
print(numpy.linalg.matrix_rank(x))

2


In [7]:
#Determinant of matrix
print(numpy.linalg.det(x))

-2.9999999999999996


In [8]:
#Inverse of matrix
print(numpy.linalg.inv(x))

[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]


In [9]:
#Eigen values of matrix
print(numpy.linalg.eig(x))

(array([-0.46410162,  6.46410162]), array([[-0.80689822, -0.34372377],
       [ 0.59069049, -0.9390708 ]]))
