<a href="https://colab.research.google.com/github/AnushaSanoop/Data-Science/blob/master/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
a=[1,5,8,9]
s=pd.Series(a)
print(s)

0    1
1    5
2    8
3    9
dtype: int64


In [ ]:
a=pd.Series([5,10,15])
print(a)
print(a.loc[2])

0     5
1    10
2    15
dtype: int64
15


In [ ]:
a=pd.Series(["Apple","Banana","grapes","Watermelon"],index=['A','B','C','D'])
print(a)

A         Apple
B        Banana
C        grapes
D    Watermelon
dtype: object


In [ ]:
a=pd.Series([15,60,45,50],index=["MCA","BCA","MSc CS","BTech"])
print(a)
print("MAximum students: ",a.max())

MCA       15
BCA       60
MSc CS    45
BTech     50
dtype: int64
MAximum students:  60


In [ ]:
x=[i for i in range(61) if((i%2==0) and (i%3==0))]
s=pd.Series(x)
print(s[1:])

1      6
2     12
3     18
4     24
5     30
6     36
7     42
8     48
9     54
10    60
dtype: int64


In [ ]:
#dataframe
data={"Percentage":[70,90,84,83,75],"Grade":['B','A+','B+','B+','B']}
d=pd.DataFrame(data,index=["Adil","Amjada","Anagha","Anjana","Anusha"])
print(d)
print(d.loc["Anjana"])

        Percentage Grade
Adil            70     B
Amjada          90    A+
Anagha          84    B+
Anjana          83    B+
Anusha          75     B
Percentage    83
Grade         B+
Name: Anjana, dtype: object


In [ ]:
#read csv file

import pandas as pd
p=pd.read_csv('/content/data.csv')
print(p.to_string())

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45   

In [ ]:
#head in pandas
import pandas as pd
p=pd.read_csv('/content/data.csv')
print(p.head())

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0


In [ ]:
#tail in pandas
import pandas as pd
p=pd.read_csv('/content/data.csv')
print(p.tail())

     Duration  Pulse  Maxpulse  Calories
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4


In [ ]:
#remove duplicates
import pandas as pd
p=pd.read_csv('/content/data.csv')
p.drop_duplicates("Duration")
print(p)

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]


In [ ]:
#CSV CREATED IN EXCEL
import pandas as pd
p=pd.read_csv('/Untitled spreadsheet - Sheet1.csv')
print(p.to_string())
p.drop_duplicates("NAME")
p.dropna()

    NAME  MARKS
0    RAM  450.0
1    SAM  480.0
2  SEETA  790.0
3    SAM  790.0
4   JOHN    NaN
5   ADAM  650.0


NAME  MARKS
0    RAM  450.0
1    SAM  480.0
2  SEETA  790.0
3    SAM  790.0
5   ADAM  650.0

In [ ]:
import pandas as pd
p=pd.read_csv('/content/data.csv')
print(p.to_string())
p.corr()

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45   

Duration     Pulse  Maxpulse  Calories
Duration  1.000000 -0.155408  0.009403  0.922717
Pulse    -0.155408  1.000000  0.786535  0.025121
Maxpulse  0.009403  0.786535  1.000000  0.203813
Calories  0.922717  0.025121  0.203813  1.000000

In [ ]:
#Transpose of a matrix
import numpy as np
a=np.matrix('[1,1,1;2,2,2;3,3,3]')
print(a)
print("Transpose=")
print(a.transpose())

[[1 1 1]
 [2 2 2]
 [3 3 3]]
Transpose=
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
#svd
import numpy as np
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Given matrix: ",A)
U,D,VT=np.linalg.svd(A)
print("U: ",U)
print("D: ",D)
print("VT:  ",VT)
A_remake=(U@np.diag(D)@VT)
print("A_remake")
print(A_remake)



Given matrix:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
U:  [[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]
D:  [1.68481034e+01 1.06836951e+00 3.33475287e-16]
VT:   [[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]
A remake
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
